#ifndef GLOBALS_H
#define GLOBALS_H

#define ANAX_ERR_INVALID_INVOCATION					-1
#define ANAX_ERR_FILE_DOES_NOT_EXIST				-2
#define ANAX_ERR_NO_MEMORY							-3
#define ANAX_ERR_TIFF_SCANLINE						-4
#define ANAX_ERR_PNG_STRUCT_FAILURE					-5

#define ANAX_RELATIVE_COLORS						0
#define ANAX_ABSOLUTE_COLORS						1

#endif

